version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-cml-bets
    environment:
      MYSQL_DATABASE: 'cml-bets'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - '3306:3306'
    networks:
      - app-network
    volumes:
      - mysql-db:/var/lib/mysql

  cml_bets-api:
    container_name: cml_bets-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-db:
